baseURL = 'https://www.offthehamsterwheel.co.uk/'
title = 'OFF THE HAMSTER WHEEL'
theme = "hugo-theme-puppet"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "guide"
name = "Countries"
url = "/series/themes-guide/"
weight = 20
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "Website"
name = "My Website"
url = "https://themadbiker.co.uk/"
weight = 100

[params]
author = "The Madbbiker"
description = "A Motorcycle Travel Blog"
keywords = "blog,motorbike,personal"
img_home = "img/main.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

[params.sidebar]
enable = true
gravatarEmail = ""
avatar = "img/profile-image.png"
bio = "A Motorcycle Travel Blog"

[params.social]
facebook = "MadBiker250"
instagram = "madbiker250"
email = "themadbiker@protonmail.com"
